version: '3.8'

services:
  postgres:
    container_name: docker_test
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=docker_test
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=204060
    ports:
      - '5431:5431'
    volumes:
      - ./PersistanceLog/postgres-data:/var/lib/postgresql
    command:
      - -p 5431